apiVersion: security.kubearmor.com/v1
kind: KubeArmorHostPolicy
metadata:
  name: account-mgmt-operations
spec:
  action: Audit
  message: "Detected Linux user or group account modification operation"
  nodeSelector:
    matchLabels:
      kubearmor.io/hostname: '*'
  process:
    matchPaths:
      - execname: chage
      - execname: chgpasswd
      - execname: chpasswd
      - execname: gpasswd
      - execname: groupadd
      - execname: groupdel
      - execname: groupmems
      - execname: groupmod
      - execname: newgrp
      - execname: newusers
      - execname: sudoedit
      - execname: useradd
      - execname: userdel
      - execname: usermod
      - execname: visudo
      - path: /usr/bin/passwd
  severity: 5
  tags:
  - MITRE_T1136_CREATE_ACCOUNT
  - MITRE_T1548_ABUSE_ELEVATION_CONTROL
  - NIST_AC-2(4)
  - STIG_RHEL-07-010200
