apiVersion: security.kubearmor.com/v1
kind: KubeArmorHostPolicy
metadata:
  name: kernel-modules
spec:
  action: Audit
  message: "Detected attempt to modify or load/unload kernel modules"
  file:
    matchDirectories:
    - dir: /etc/modprobe.d/
      readOnly: true
      recursive: true
    - dir: /etc/modules-load.d/
      readOnly: true
      recursive: true
    matchPaths:
    - path: /etc/modules
      readOnly: true
  nodeSelector:
    matchLabels:
      kubearmor.io/hostname: '*'
  process:
    matchPaths:
    - execname: kmod
  severity: 4
  tags:
   - MITRE_T1547.006_KERNEL_MODULE_PERSISTENCE
   - MITRE_T1200_HARDWARE_FIRMWARE
   - NIST_SI-7
   - STIG_UBTU-20-010297
