apiVersion: security.kubearmor.com/v1
kind: KubeArmorHostPolicy
metadata:
  name: net-tools
spec:
  action: Audit
  message: "Detected execution of network monitoring or scanning tools"
  nodeSelector:
    matchLabels:
      kubearmor.io/hostname: '*'
  process:
    matchPath:
    - execname: mitmproxy
    - execname: nmap
    - execname: tcpdump
    - execname: tshark
    - execname: zmap
    - execname: nc        
    - execname: socat     
    - execname: masscan   
    - execname: bettercap 
  severity: 5
  tags:
  - MITRE_T1049_SYSTEM_NETWORK_CONNECTIONS_DISCOVERY
  - MITRE_T1040_NETWORK_SNIFFING
  - NIST_SI-4
  - PCI_DSS_11.4

