apiVersion: security.kubearmor.com/v1
kind: KubeArmorHostPolicy
metadata:
  name: node-file-integrity-monitoring
spec:
  action: Audit
  message: "Detected and prevented compromise File integrity"
  nodeSelector:
    matchLabels:
      kubearmor.io/hostname: '*'
  file:
    matchDirectories:
    - dir: /bin/
      readOnly: true
      recursive: true
    - dir: /sbin/
      readOnly: true
      recursive: true
    - dir: /usr/bin/
      readOnly: true
      recursive: true
    - dir: /usr/sbin/
      readOnly: true
      recursive: true
    - dir: /lib/
      readOnly: true
      recursive: true
    - dir: /lib64/
      readOnly: true
      recursive: true
    - dir: /usr/lib/
      readOnly: true
      recursive: true
    - dir: /boot/
      readOnly: true
      recursive: true
    - dir: /boot/grub/
      readOnly: true
      recursive: true
  severity: 2
  tags:    
   - MITRE_T1036_MASQUERADING
   - MITRE_T1565_DATA_MANIPULATION
   - NIST_SI-7
   - PCI_DSS_11.5
