apiVersion: security.kubearmor.com/v1
kind: KubeArmorHostPolicy
metadata:
  name: package-management-tools
spec:
  action: Audit
  message: "Detected execution of package management tools"
  nodeSelector:
    matchLabels:
      kubearmor.io/hostname: '*'
  process:
    matchPaths:
    - execname: apk
    - execname: apt
    - execname: make
    - execname: gdebi
      # RHEL / Fedora / CentOS
    - execname: dnf
    - execname: rpm
    - execname: yum
      # SUSE
    - execname: zypper
      # Arch / Manjaro
    - execname: pacman
    - execname: makepkg
    - execname: yaourt
  severity: 8
  tags:
   - MITRE_T1072_SOFTWARE_DEPLOYMENT_TOOLS
   - NIST_CM-6
   - PCI_DSS_6.2
 
