apiVersion: security.kubearmor.com/v1
kind: KubeArmorHostPolicy
metadata:
  name: ssh-login
spec:
  action: Audit
  message: "Detected login/execution through SSH"
  nodeSelector:
    matchLabels:
      kubearmor.io/hostname: '*'
  process:
    matchPaths:
    - fromSource:
      - path: /usr/sbin/sshd
      path: /bin/bash
    - fromSource:
      - path: /usr/sbin/sshd
      path: /bin/dash
    - fromSource:
      - path: /usr/sbin/sshd
      path: /bin/sh
  severity: 6
  tags:
  - MITRE_T1078_VALID_ACCOUNTS
  - NIST_IA-2
  - PCI_DSS_8.2
  
