apiVersion: security.kubearmor.com/v1
kind: KubeArmorHostPolicy
metadata:
  name: su-access
spec:
  action: Audit
  message: "Detected potential privilege escalation via su or sudo command"
  nodeSelector:
    matchLabels:
      kubearmor.io/hostname: '*'
  process:
    matchPaths:
    - execname: su
  severity: 8
  tags:
   - MITRE_T1548.003_ABUSE_ELEVATION_CONTROL
   - NIST_AC-6
   - PCI_DSS_7.2
