apiVersion: security.kubearmor.com/v1
kind: KubeArmorHostPolicy
metadata:
  name: system-credentials
spec:
  action: Audit
  message: "Detected attempt to modify system credentials"
  nodeSelector:
    matchLabels:
      kubearmor.io/hostname: '*'
  file:
    matchPaths:
    - path: /etc/passwd
      readOnly: true
    - path: /etc/shadow
      readOnly: true
    - path: /root/.ssh/authorized_keys
      readOnly: true
    - path: /etc/ssh/sshd_config
      readOnly: true
    - path: /etc/ca-certificates.conf
      readOnly: true
  process:
    matchPaths:
    - execname: certutil
    - execname: ssh-keygen
    - execname: passwd
    - execname: chpasswd
    - execname: openssl
  severity: 3
  tags:
  - MITRE_T1552_UNSECURED_CREDENTIALS
  - NIST_IA-5
  - PCI_DSS_8.2.1

