apiVersion: security.kubearmor.com/v1
kind: KubeArmorPolicy
metadata: 
  name: maintenance-tool-access
  namespace: default
spec: 
  message: "restricted maintenance tool access attempt detected"
  selector: 
    matchLabels: 
      kubearmor.io/container.name: alpine
  tags: 
    - PCI_DSS
    - MITRE
    - MITRE_TA0004_T1548
    - MITRE_TA0003_T1543.002
    - MITRE_T1553
  severity: 1
  process:
      matchDirectories:
      - dir: /sbin/
        recursive: true
  action: Audit
