apiVersion: security.kubearmor.com/v1
kind: KubeArmorPolicy
metadata:
  name: ksp-near-rt-ric-e2mgr-zero-trust
  namespace: nearrt-sec-plat
spec:
  selector:
    matchLabels:
      app: nearrt-sec-plat-e2mgr

  file:
    matchDirectories:
    - dir: /
      recursive: true
    - dir: /etc/
      recursive: true
      action: Audit
    - dir: /var/run/secrets/kubernetes.io/serviceaccount/
      action: Block
      message: unauthorized access to kubernetes service account
    - dir: /var/run/secrets/kubernetes.io/serviceaccount/
      action: Allow
      fromSource:
      - path: /opt/E2Manager/main
    - dir: /opt/E2Manager/
      recursive: true
      action: Block
    - dir: /opt/E2Manager/
      recursive: true
      fromSource:
      - path: /opt/E2Manager/main
    - dir: /etc/config
      recursive: true
      action: Block
    - dir: /etc/config
      recursive: true
      fromSource:
      - path: /opt/E2Manager/main
  process:
    matchDirectories:
    - dir: /
      recursive: true
      action: Audit
    matchPaths:
    - path: /usr/bin/containerd-shim-runc-v2
    - path: /opt/E2Manager/main
    - path: /usr/bin/sh
    - path: /usr/bin/dash
  network:
    matchProtocols:
    - fromSource:
      - path: /opt/E2Manager/main
      protocol: raw
    - fromSource:
      - path: /opt/E2Manager/main
      protocol: udp
    - fromSource:
      - path: /opt/E2Manager/main
      protocol: tcp
  action: Allow
  severity: 1
