apiVersion: security.kubearmor.com/v1
kind: KubeArmorPolicy
metadata:
  name: ksp-near-rt-ric-appmgr-zero-trust
  namespace: nearrt-sec-plat
spec:
  selector:
    matchLabels:
      app: nearrt-sec-plat-appmgr

  file:
    matchDirectories:
    - dir: /
      recursive: true
    - dir: /etc/ 
      recursive: true
      action: Audit 
    - dir: /var/run/secrets/kubernetes.io/serviceaccount/
      action: Block
      message: unauthorized access to kubernetes service account
    - dir: /var/run/secrets/kubernetes.io/serviceaccount/
      action: Allow
      fromSource:
      - path: /opt/xAppManager/appmgr
    - dir: /opt/ric/
      recursive: true
      action: Block
    - dir: /opt/ric/
      recursive: true
      fromSource:
      - path: /opt/xAppManager/appmgr
  process:
    matchDirectories:
    - dir: /
      recursive: true
      action: Audit
    matchPaths:
    - path: /usr/bin/containerd-shim-runc-v2
    - path: /opt/xAppManager/appmgr-entrypoint.sh
    - path: /opt/xAppManager/appmgr
    - path: /usr/bin/sh
    - path: /usr/bin/dash
  network:
    matchProtocols:
    - fromSource:
      - path: /opt/xAppManager/appmgr
      protocol: raw
    - fromSource:
      - path: /opt/xAppManager/appmgr
      protocol: udp
    - fromSource:
      - path: /opt/xAppManager/appmgr
      protocol: tcp
  action: Allow
  severity: 1
