apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: allow-only-trusted-registry
spec:
  validationFailureAction: Audit 
  background: true
  rules:
    - name: validate-image-registry
      match:
        resources:
          kinds:
            - Pod
          namespaces:
            - nearrt-sec-plat 
      validate:
        message: "Only images from jfrog.rsym-cicd.blr.rsicdcdns.lab are allowed."
        pattern:
          spec:
            containers:
              - image: "jfrog.rsym-cicd.blr.rsicdcdns.lab/*"
