apiVersion: security.kubearmor.com/v1
kind: KubeArmorClusterPolicy
metadata:
  name: audit-pen-test-recon-tools
  annotations:
    app.accuknox.com/type: harden
spec:
  action: Audit
  severity: 3
  message: "Detected Penetration Testing tool execution"  
  process:
    matchPaths:
      # Recon & Network Scanners
      - execname: nmap
      - execname: masscan
      - execname: zmap
     
      # Password / Hash Crackers
      - execname: hydra
      - execname: john        
      - execname: hashcat
      - execname: medusa
      - execname: patator
  tags:
    - MITRE_T1110_BRUTE_FORCE
    - NIST_SI-4   
    - PCI_DSS_11.5 
