apiVersion: security.kubearmor.com/v1
kind: KubeArmorClusterPolicy
metadata:
  name: audit-network-packet-tools
  annotations:
    app.accuknox.com/type: harden
spec:
  action: Audit
  severity: 3
  message: "Detected use of network packet manipulation tool"
  process:
    matchPaths:
      - execname: iptables
      - execname: ip6tables
      - execname: nft
      - execname: nftables
      - execname: ip
      - execname: iproute2
      - execname: tc
      - execname: brctl
      - execname: arp
      - execname: arptables
      - execname: ebtables
      - execname: ethtool
  selector:
    matchExpressions:
      - key: namespace
        operator: NotIn
        values:
          - kube-system   # exempt system namespace
  tags:
    - MITRE_TA0005_T1562.004
    - MITRE_TA0005_T1601
    - MITRE_TA0003_T1543
    - MITRE
    - NIST_CM-7
    - PCI_DSS_10.2.6
