apiVersion: security.kubearmor.com/v1
kind: KubeArmorClusterPolicy
metadata:
  annotations:
    app.accuknox.com/type: harden
  name: cronjob-cfg
spec:
  action: Audit
  severity: 5
  message: "Detected access to cron job files/directories"
  file:
    matchDirectories:
      - dir: /etc/cron.d/
        recursive: true
      - dir: /etc/cron.daily/
        recursive: true
      - dir: /etc/cron.hourly/
        recursive: true
      - dir: /etc/cron.monthly/
        recursive: true
      - dir: /etc/cron.weekly/
        recursive: true
      - dir: /var/cron/
        recursive: true
      - dir: /var/spool/cron/
        recursive: true
    matchPaths: 
      - path: /etc/crontab
        readOnly: true
      - path: /etc/anacrontab   # Runs scheduled tasks (cron jobs) that were missed while the system was off.
        readOnly: true
      - path: /etc/cron.allow
        readOnly: true
      - path: /etc/cron.deny
        readOnly: true
  selector:
    matchExpressions:
      - key: namespace
        operator: NotIn
        values:
          - kube-system
  tags:
    - CIS
    - CIS_5.1_Configure_Cron
    - CIS_Linux
    - NIST
    - NIST_800-53_SI-4
    - SI-4
