apiVersion: security.kubearmor.com/v1
kind: KubeArmorClusterPolicy
metadata:
  annotations:
    app.accuknox.com/type: harden
  name: crypto-miners
spec:
  action: Block
  severity: 3
  message: "Blocked Cryptominer"
  process:
    matchPaths:
      # DERO cryptominers
      - execname: dero-miner-linux-amd64
      - execname: dero-wallet-cli-linux-amd64
      - execname: dero
      - execname: derod-linux-amd64

      # Monero CPU/GPU miners
      - execname: xmrig
      - execname: xmrig-stak
      - execname: minerd
      - execname: mminerd
      - execname: cpuminer
      - execname: sgminer
      - execname: ccminer
  tags:
    - MITRE_TA0040_T1496
    - MITRE_TA0002_T1204.002
    - MITRE
    - MITRE_TA0003_T1053.003
    - NIST_CM-7
    - PCI_DSS_6.2
