apiVersion: security.kubearmor.com/v1
kind: KubeArmorClusterPolicy
metadata:
  name: audit-external-device
  annotations:
    app.accuknox.com/type: harden
spec:
  action: Audit
  severity: 3
  message: "Detected modification of external device access"
  selector:
    matchExpressions:
      - key: namespace
        operator: NotIn
        values:
          - kube-system   
  process:
    matchPaths:
      - execname: mount
      - execname: umount
      - execname: fdisk
      - execname: cfdisk
      - execname: sfdisk
      - execname: parted
      - execname: mkfs
      - execname: fsck
      - execname: lsblk
      - execname: blkid
      - execname: losetup
      - execname: kpartx
      - execname: qemu-nbd
      - execname: mountpoint
  tags:
    - MITRE_TA0008_T1091
    - MITRE_TA0009_T1074
    - MITRE_TA0009_T1005
    - MITRE
    - NIST_DE.CM-1
    - PCI_DSS_10.2.3
