apiVersion: security.kubearmor.com/v1
kind: KubeArmorClusterPolicy
metadata:
  annotations:
    app.accuknox.com/type: harden
  name: file-integrity-monitoring
spec:
  action: Audit
  message: "Detected attempted modification of core system binary/library directories (file integrity)"
  file:
    matchDirectories:
      - dir: /bin/
        recursive: true
        readOnly: true
      - dir: /sbin/
        recursive: true
        readOnly: true
      - dir: /usr/bin/
        recursive: true
        readOnly: true
      - dir: /usr/sbin/
        recursive: true
        readOnly: true
      - dir: /boot/
        recursive: true
        readOnly: true
  selector:
    matchExpressions:
      - key: namespace
        operator: NotIn
        values:
          - kube-system
  severity: 1
  tags:
    - MITRE_T1036_MASQUERADING
    - NIST_800-53_AU-2
    - PCI_DSS_11.5.1
