apiVersion: admission.accuknox.com/v1
kind: AdmissionPolicy
metadata:
  annotations:
    app.accuknox.com/type: harden
  labels:
    app.kubernetes.io/name: admission-controller
    name: harden-deny-privileged-pods
spec:
  denyPrivilegedPod:
    action: Audit
    message: "Detected privileged pod creation attempt"
    ignoreNamespaces:
      - kube-system   # Monitoring, Logging namespaces could be added
