apiVersion: security.kubearmor.com/v1
kind: KubeArmorClusterPolicy
metadata:
  name: k8s-client-tool-exec
  annotations:
    app.accuknox.com/type: harden
spec:
  action: Audit
  message: "Detected execution of Kubernetes client tools or container runtime CLIs"
  severity: 5
  selector:
    matchExpressions:
      - key: namespace
        operator: NotIn
        values:
          - kube-system
  process:
    matchPaths:
      # Kubernetes client tools
      - execname: kubectl
      - execname: oc

      # Container runtime CLIs
      - execname: crictl
      - execname: docker
      - execname: ctr
      - execname: nerdctl
      - execname: podman
  tags:
    - MITRE
    - MITRE_T1609_CONTAINER_ADMINISTRATION_COMMAND
    - MITRE_T1610_DEPLOY_CONTAINER
    - MITRE_TA0002_EXECUTION
    - NIST
    - NIST_800-53
    - NIST_800-53_AU-2
    - NIST_800-53_SI-4
