# CHANGE LOG: Added additional admin directories (/usr/sbin, /usr/local/sbin)

apiVersion: security.kubearmor.com/v1
kind: KubeArmorClusterPolicy
metadata:
  annotations:
    app.accuknox.com/type: harden
  name: maint-tools-access
spec:
  action: Audit
  message: "Detected restricted maintenance tool access attempt"
  process:
    matchDirectories:
      - dir: /sbin/
        recursive: true
      - dir: /usr/sbin/
        recursive: true
      - dir: /usr/local/sbin/
        recursive: true
  selector:
    matchExpressions:
      - key: namespace
        operator: NotIn
        values:
          - kube-system
  severity: 1
  tags:
    - MITRE_T1543_003_CREATE_MODIFY_SYSTEM_PROCESS
    - NIST_RS.AN-
    - PCI_DSS_2.2.2
