apiVersion: security.kubearmor.com/v1
kind: KubeArmorClusterPolicy
metadata:
  name: prevent-kubectl-cp
  annotations:
    app.accuknox.com/type: harden
spec:
  action: Block
  message: "Blocked kubectl cp operation"
  selector:
    matchExpressions:
      - key: namespace
        operator: NotIn
        values:
          - kube-system
  process:
    matchPaths:  
    - execname: tar  
  severity: 7
  tags:
    - MITRE_T1105
    - NIST_CM-7
    - PCI_DSS_10.2.6
   
