apiVersion: security.kubearmor.com/v1
kind: KubeArmorClusterPolicy
metadata:
  annotations:
    app.accuknox.com/type: harden
  name: remote-file-copy
spec:
  action: Audit
  message: "Detected Remote file copy utility execution"
  process:
    matchPaths:
      - execname: scp
      - execname: rsync
      - execname: sftp
      - execname: ftp
      - execname: netkit-ftp
  selector:
    matchExpressions:
      - key: namespace
        operator: NotIn
        values:
          - kube-system
  severity: 5
  tags:
    - MITRE_T1552_UNSECURED_CREDENTIALS
    - NIST_800-53_SI
    - PCI_DSS_4.1
