apiVersion: security.kubearmor.com/v1
kind: KubeArmorClusterPolicy
metadata:
  name: trusted-cert-mod
  annotations:
    app.accuknox.com/type: harden
spec:
  action: Audit
  severity: 2
  message: "Detected attempt to modify trusted certificates"
  selector:
    matchExpressions:
      - key: namespace
        operator: NotIn
        values:
          - kube-system
  file:
    matchDirectories:
      - dir: /etc/pki/
        recursive: true
        readOnly: true
      - dir: /etc/ssl/
        recursive: true
        readOnly: true
      - dir: /usr/local/share/ca-certificates/
        recursive: true
        readOnly: true
  tags:
    - MITRE_TA0005_T1562
    - MITRE_TA0006_T1557
    - MITRE_TA0005_T1553.004
    - MITRE
    - NIST_PR.PT-1
    - PCI_DSS_10.5.5
