apiVersion: security.kubearmor.com/v1
kind: KubeArmorClusterPolicy
metadata:
  annotations:
    app.accuknox.com/type: harden
  name: write-under-dev-dir
spec:
  action: Audit
  file:
    matchDirectories:
    - dir: /dev/
      readOnly: true
      recursive: true
  message: "Detected File creation under /dev/ directory"
  selector:
    matchExpressions:
    - key: namespace
      operator: NotIn
      values:
      - kube-system
  severity: 5
  tags:
    - MITRE_TA0005_T1564.001
    - MITRE_TA0009_T1074
    - MITRE_TA0004_T1068
    - MITRE
    - NIST_PR.DS-8 
    - PCI_DSS_5.1
