#Added Audit action

apiVersion: security.kubearmor.com/v1
kind: KubeArmorClusterPolicy
metadata:
  annotations:
    app.accuknox.com/type: harden
  name: write-etc-dir
spec:
  action: Audit
  file:
    matchDirectories:
    - dir: /etc/
      readOnly: true
      recursive: true
  message: "Detected File creation under /etc/ directory"
  selector:
    matchExpressions:
    - key: namespace
      operator: NotIn
      values:
      - kube-system
  severity: 5
  tags:
    - MITRE_T1036_MASQUERADING
    - NIST_800-53_SI-7
    - PCI_DSS_2.2.2 
