apiVersion: security.kubearmor.com/v1
kind: KubeArmorPolicy
metadata:
  name: ksp-non-rt-ric-fm-adaptor-zero-trust
  namespace: nonrt-sec-plat
spec:
  action: Allow  
  selector:
    matchLabels:
      app.kubernetes.io/name: fault-oam
  file:
    matchDirectories:
    - dir: /
      recursive: true
    - dir: /etc/
      recursive: true
      action: Audit
    - dir: /home/ricuser/smoadaptor/
      recursive: true
      action: Block
    - dir: /home/ricuser/smoadaptor/
      recursive: true
      fromSource:
      - path: /home/ricuser/smoadaptor/fm
    - dir: /opt/ric/
      recursive: true
      action: Block
    - dir: /opt/ric/
      recursive: true
      fromSource:
      - path: /home/ricuser/smoadaptor/fm
    - dir: /data/
      recursive: true
      action: Block
    - dir: /data/
      recursive: true
      fromSource:
      - path: /home/ricuser/smoadaptor/fm
    - dir: /var/run/secrets/kubernetes.io/serviceaccount/
      action: Block
      message: unauthorized access to kubernetes service account
    - dir: /var/run/secrets/kubernetes.io/serviceaccount/
      action: Allow
      fromSource:
      - path: /home/ricuser/smoadaptor/fm
  process:
    matchDirectories:
    - dir: /
      recursive: true
      action: Audit
    matchPaths:
    - path: /usr/bin/containerd-shim-runc-v2
    - path: /home/ricuser/smoadaptor/fm
    - path: /bin/sh
    - path: /bin/dash
  network:
    matchProtocols:
    - fromSource:
      - path: /home/ricuser/smoadaptor/fm
      protocol: raw
    - fromSource:
      - path: /home/ricuser/smoadaptor/fm
      protocol: udp
    - fromSource:
      - path: /home/ricuser/smoadaptor/fm
      protocol: tcp
  severity: 1
